language: node_js
node_js:
    - "lts/*"
script: true
before_deploy:
  - npm i postmark-cli -g
deploy:
  provider: script
  script: postmark templates push ./templates -f
  on:
    branch: master 
after_deploy:
  - postmark email raw -f=support@pigeonbot.com -t=derek@wildbit.com --subject="[Travis CI] Templates pushed" --text="Templates have been pushed to Postmark - $TRAVIS_BUILD_WEB_URL"
