version: 2
jobs:
  build:
    branches:
      only: master
    machine: true
    steps:
      - checkout
      - run:
          name: Install Postmark-cli
          command: |
            npm i postmark-cli -g
      - run:
          name: Push templates to Postmark
          command: |
            postmark templates push ./templates -f
      - run:
       	   name: Send notification email
           command: |
              postmark email raw -f=support@pigeonbot.com -t=derek@wildbit.com --subject="[CircleCI] Templates pushed" --text="Templates have been pushed to Postmark - $CIRCLE_BUILD_URL"
